import { test, expect } from '@playwright/test';

test('real small model follows audio captured through browser AudioWorklet', async ({ page }) => {
  test.skip(!process.env.TEST_AUDIO_PATH, 'Set TEST_AUDIO_PATH to a local spoken WAV fixture.');
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const sent: any[] = [], received: any[] = [];
  let sockets = 0;
  page.on('websocket', socket => {
    sockets++;
    socket.on('framesent', frame => { if (typeof frame.payload === 'string') sent.push(JSON.parse(frame.payload)); });
    socket.on('framereceived', frame => { if (typeof frame.payload === 'string') received.push(JSON.parse(frame.payload)); });
  });
  await page.goto('/');
  await page.getByRole('button', {name:'编辑讲稿',exact:true}).click();
  await page.getByRole('textbox', {name:'讲稿正文'}).fill('大家晚上好，欢迎来到今天的直播。\n\n今天想和大家聊一件很简单的事，怎样把一场直播讲得更自然。我们不需要记住每一个字，只需要知道自己想表达什么，然后把话说清楚。');
  await page.getByRole('button', {name:'保存并使用'}).click();
  const popupEvent = page.waitForEvent('popup');
  await page.getByRole('button', {name:'主播窗口',exact:true}).click();
  const presenter = await popupEvent;
  await expect(presenter.locator('article.current')).toHaveAttribute('data-paragraph','0');
  await expect(page.getByRole('button', {name:'开始识别',exact:true})).toBeEnabled({timeout:15000});
  await page.getByRole('button', {name:'开始识别',exact:true}).click();
  await expect(page.getByRole('button', {name:'停止识别',exact:true})).toBeVisible({timeout:15000});
  const initial = sent.find(message => message.type === 'start');
  expect(initial.tracking.similarity).toBe(.77);
  await page.getByRole('button', { name: '提词设置', exact: true }).click();
  await page.getByRole('radio', { name: '灵敏 1 次失配' }).check();
  await page.getByRole('radio', { name: '长距离 800 字' }).check();
  await expect.poll(() => received.filter(message => message.type === 'tracking_configured').length).toBe(2);
  expect(sent.filter(message => message.type === 'tracking').at(-1)).toMatchObject({ generation: initial.generation, tracking: { recovery_misses: 1, max_jump_chars: 800 } });
  expect(sent.filter(message => message.type === 'seek')).toHaveLength(0);
  await page.getByRole('button', { name: '关闭设置' }).click();
  await page.locator('.prompter-scroll').hover(); await page.mouse.wheel(0, 650);
  await page.waitForTimeout(200);
  const browsed = await page.locator('.prompter-scroll').evaluate(el => el.scrollTop);
  await expect(page.getByRole('button', { name: '回到跟读位置', exact: true })).toBeVisible();
  await expect(page.locator('.transcript-feed')).toContainText('大家', {timeout:25000});
  await expect(page.locator('.stage-bottom')).toContainText('第 2 段', {timeout:20000});
  await expect(presenter.locator('article.current')).toHaveAttribute('data-paragraph','1');
  expect(await page.locator('.prompter-scroll').evaluate(el => el.scrollTop)).toBeCloseTo(browsed, 0);
  expect(sent.filter(message => message.type === 'seek')).toHaveLength(0);
  await page.getByRole('button', { name: '回到跟读位置', exact: true }).click();
  await expect(page.getByRole('button', { name: '回到跟读位置', exact: true })).toHaveCount(0);
  expect(sent.filter(message => message.type === 'seek')).toHaveLength(0);
  const distance = await page.locator('.prompter-scroll').evaluate(box => Math.abs(box.querySelector('[data-active-line="true"]')!.getBoundingClientRect().top - box.getBoundingClientRect().top - box.clientHeight * .28));
  expect(distance).toBeLessThan(3);
  await page.getByRole('button',{name:'实时转写',exact:true}).click();
  expect(sent.filter(message => message.type === 'seek').at(-1).tracking.max_jump_chars).toBe(800);
  await expect(presenter.locator('.live-text')).toContainText('大家');
  await page.locator('.prompter-scroll').hover(); await page.mouse.wheel(0, -650);
  await page.waitForTimeout(200);
  const transcriptBefore = await page.locator('.live-text').innerText();
  const transcriptScroll = await page.locator('.prompter-scroll').evaluate(el => el.scrollTop);
  const seekCount = sent.filter(message => message.type === 'seek').length;
  await expect.poll(() => page.locator('.live-text').innerText(), { timeout: 15000 }).not.toBe(transcriptBefore);
  expect(await page.locator('.prompter-scroll').evaluate(el => el.scrollTop)).toBeCloseTo(transcriptScroll, 0);
  await page.getByRole('button', { name: '回到最新', exact: true }).click();
  expect(sent.filter(message => message.type === 'seek')).toHaveLength(seekCount);
  const tailGap = await page.locator('.prompter-scroll').evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop);
  expect(tailGap).toBeLessThan(2);
  await page.getByRole('button', {name:'停止识别',exact:true}).click();
  await expect(page.getByRole('button', {name:'开始识别',exact:true})).toBeEnabled({timeout:20000});
  await expect(page.locator('.message-bar.error')).toHaveCount(0);
  expect(errors).toEqual([]);
  expect(sockets).toBe(1);
  await presenter.close();
});
